### PR TITLE
port helm mode manager to ivy

### PR DESCRIPTION
**Pull request by jeizsm**
Hi, I recently switch from helm to ivy in spacemacs but I found few things is missed, one of them is [helm-mode-manager](https://github.com/istib/helm-mode-manager), so I ported it.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks, looks nice. One remark is that `counsel-list-major-modes` shouldn't be `interactive`.

Are you willing to get an Emacs Copyright Assignment? Ivy is in GNU ELPA, so I need contributors to get a CA for merging more than 15 lines total.

**Comment by jeizsm** [comment]
>Thanks, looks nice. One remark is that counsel-list-major-modes shouldn't be interactive.

Done
>Are you willing to get an Emacs Copyright Assignment? Ivy is in GNU ELPA, so I need contributors to get a CA for merging more than 15 lines total.

What I need to do?

**Comment by abo-abo** [comment]
Send one email using this [form](http://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future). In the "name of program" just write "Emacs", it will work for everything related to Emacs - core, Org-mode, ELPA.

They'll send you a PDF to sign and send back to them. It takes around a month for them to process the letter, maybe less.

**Comment by abo-abo** [comment]
Send one email using this [form](http://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future). In the "name of program" just write "Emacs", it will work for everything related to Emacs - core, Org-mode, ELPA.

They'll send you a PDF to sign and send back to them. It takes around a month for them to process the letter, maybe less.

**Comment by jeizsm** [comment]
Ok, thanks. I send the letter

**Comment by abo-abo** [comment]
Any progress on this? Maybe you should email the FSF clerk if you haven't received an update.

**Comment by abo-abo** [comment]
Thanks, merged partially. Since `counsel-minor` was added in the meantime, and the remaining code fits in the 15 line limit.

**Pull request closed without merging**
