### PR TITLE
counsel.el (counsel-git-grep-skip-counting-lines): New defcustom

### PR DESCRIPTION
**Pull request by edkolev**
Refs #524

### CODE REVIEW

**Comment by edkolev** [comment]
As discussed in #524.

Let me know in case the PR can be improved.

**Comment by abo-abo** [comment]
There's a problem: when `counsel-git-grep-skip-counting-lines` is non-nil, `shell-command-to-string` gets called: it is sync so you wait for all results before you can enter a new key.  `counsel--gg-candidates` should be called to get candidates async.

**Comment by edkolev** [comment]
Thanks for catching this! I modified `counsel-git-grep-function` to call the async `counsel--gg-candidates`.

For testing purposes, I simulated a slow git command with: `counsel-git-grep-cmd-default` set to `"sleep 2 && git --no-pager grep --full-name -n --no-color -i -e '%s'"`

The commit is amended. Again, let me know if I can improve anything.

**Comment by abo-abo** [comment]
Thanks. It seems you don't yet have an Emacs CA. And your cumulative contributions are above the 15 line limit where you don't need it.  See README on more info on getting an Emacs Copyright Assignment.

**Comment by edkolev** [comment]
Thanks, I sent the initial email, I'll write here when I get the CA.

**Comment by abo-abo** [comment]
Thanks.

**Comment by edkolev** [comment]
Hi, I now have a signed (by me & FSF) CA in digital format.

**Comment by abo-abo** [comment]
Thanks.

**Pull request closed without merging**
