### PR TITLE
ivy.el (ivy--magic-file-slash): Fix dir expansion

### PR DESCRIPTION
**Pull request by basil-conto**
Please review each commit in turn. The first commit addresses #1829 and its commentary follows. The remaining commits are merely logic simplifications of the surrounding code.

Cc: @dwang20151005

---

Expand `ivy-text` against `ivy--directory`, not `default-directory`.

Perhaps the commentary of [1] was correct in that `default-directory` should be bound to `ivy--directory` more generally here.

[1]: `ivy.el` (`ivy--magic-file-slash`): Change priority in `cond`
  2017-04-13 17:09:47 +0200 f94c15c8cb40f7a9959a3ffcd2052bb3a118eb3f

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. Would be cool to eventually add some tests to this.

**Comment by dwang20151005** [comment]
Does "closed" mean this PR was accepted and merged, or rejected without merge?

**Comment by abo-abo** [comment]
@dwang20151005  Means it's merged. You can check it if you look at the commit message.

Github doesn't recognize it as merged because I had to rebase the PR on top of new changes.

**Comment by dwang20151005** [comment]
Got it, thanks.  (Sorry, not familiar with git/github.)

**Pull request closed without merging**
