### PR TITLE
ivy.el: Allow toggling of sorting in ivy-read

### PR DESCRIPTION
**Pull request by justbur**
Modify `ivy-sort-functions-alist` to allow a list of sorting functions to apply to
a collection. The car of this list is the current one. `ivy-rotate-sort` then
rotates this list through the different possibilities. I bound it to `C-c C-s`. Here
is a simple example to illustrate.

```elisp
(setq ivy-sort-functions-alist
  '((read-file-name-internal .
    (ivy-sort-file-function-default string-lessp string-greaterp))
    (internal-complete-buffer . nil)
    (counsel-git-grep-function . nil)
    (Man-goto-section . nil)
    (org-refile . nil)
    (t . string-lessp)))
```

`M-x find-file RET C-c C-s` now switches from the default sorting to using
`string-lessp`. `C-c C-s` again switches to string-greaterp and so on.

ivy.el (ivy-sort-functions-alist): Allow list in cdr of each cell
ivy.el (ivy-rotate-sort): Add
ivy.el (ivy--sort-function): Add and use for
lookup in ivy-sort-functions-alist

### CODE REVIEW

**Comment by justbur** [comment]
This is just an idea. I'm sure it can be improved.

**Comment by justbur** [comment]
Here's a slightly more interesting example that sorts by position in `recentf-list` if found.

```elisp
(defun recentf-lessp (x y)
  (unless recentf-mode
    (recentf-mode))
  (let* ((recent (mapcar 'substring-no-properties recentf-list))
         (xi (cl-position x recent))
         (yi (cl-position y recent)))
    (or (and xi (null yi))
        (and xi (<= xi yi))
        (and (null xi) (null yi)))))

(setq ivy-sort-functions-alist
      '((read-file-name-internal . (recentf-lessp ivy-sort-file-function-default))
        (internal-complete-buffer)
        (counsel-git-grep-function)
        (Man-goto-section)
        (org-refile)
        (t . string-lessp)))
```

**Comment by abo-abo** [comment]
Nice idea, thanks. Would be nice to include something sensible in `ivy-sort-functions-alist`, so that <kbd>C-c C-s</kbd> isn't a no-op by default.
Additionally, would be nice to have the feedback in the <kbd>C-o</kbd> hydra, like there already is for the current action. Maybe <kbd>C-o S</kbd> would toggle the sorting and print the sorting function symbol name somewhere.

**Comment by justbur** [comment]
> Nice idea, thanks. Would be nice to include something sensible in ivy-sort-functions-alist, so that C-c C-s isn't a no-op by default.
Additionally, would be nice to have the feedback in the C-o hydra, like there already is for the current action. Maybe C-o S would toggle the sorting and print the sorting function symbol name somewhere.

I agree. I just wasn't sure of the best way to provide feedback.

**Pull request closed without merging**
