### PR TITLE
Add ./ and ../ to ivy--magic-file-slash.

### PR DESCRIPTION
**Pull request by Yevgnen**
Just a very small modification for users from `helm` :-)

### CODE REVIEW

**Comment by abo-abo** [comment]
Doesn't the input `./` and `../` already work correctly?

**Comment by Yevgnen** [comment]
Sorry, I should test it with `emacs -Q` first. Now I find that it. When `ivy-extra-directories` is set to `nil`, it doesn't work. I try ignore the `.` and `..` in the candidates, but unexpectedly make `./` and `../` fail. Should this be an issue ?

**Comment by basil-conto** [comment]
> When `ivy-extra-directories` is set to `nil`, it doesn't work. I try ignore the `.` and `..` in the candidates, but unexpectedly make `./` and `../` fail.

I don't understand your description, so a step-by-step recipe contrasting the behaviour you expect/desire with the actual behaviour you see would be nice.

**Comment by Yevgnen** [comment]
I've forgotten what I'm trying to do. Better to close this now. Sorry.

**Pull request closed without merging**
