### PR TITLE
Add ivy-magic-root-slash

### PR DESCRIPTION
**Pull request by amosbird**

### CODE REVIEW

**Comment by abo-abo** [comment]
This feature will limit the functionality of other features, like `/ssh:` and `/sudo:`.

**Comment by amosbird** [comment]
hmm, isn't `ssh:` and `sudo:` start with `/` too? what's the limitation?

**Comment by abo-abo** [comment]
With ivy, you can open sudo in current directory with `C-x C-f /sudo:: C-j`. This feature got broken a bit, I fixed it just now. With your change, `sudo` will only be possible from  root directory, so you'd have to navigate all the way back.

**Comment by abo-abo** [comment]
With `/ssh:`, current directory is not an issue. But until you press `C-j`, you can still back out of changing your current directory. With your change, you won't be able to.

With the default completion, the full path is editable, so backing out of changing the current dir is not a concern there.

**Comment by amosbird** [comment]
ok, so how about using `//` as a magic string?

**Comment by abo-abo** [comment]
> ok, so how about using // as a magic string?

That's what's used right now. Is that not the case for you?

**Comment by amosbird** [comment]
Ah, all right. Thanks!

**Pull request closed without merging**
