### PR TITLE
Add option to jump directly to an imenu candidate

### PR DESCRIPTION
**Pull request by vermiculus**
If the symbol at point is a candidate, a new argument to `counsel-imenu`
will let you jump right to that symbol without being prompted by
`ivy-read`.

This feature was requested [on reddit][1].  I'm not entirely sure
`counsel` is the best place for this kind of functionality, though.  Is
there any precedent in the package for this kind of behavior?

If not, I'm hesitant to introduce this -- a different add-on package for
user-level gimmicks might be better suited for such a microenhancement.

[1]: https://redd.it/52vo6w

### CODE REVIEW

**Comment by vermiculus** [comment]
Ah, butts – give me a few moments to pull out the changes from the other PR. I must've made those commits on `master` – forgive me while I figure out [this new tool](https://hub.github.com/) 😄

**Comment by vermiculus** [comment]
I realize this will be stale until the CA goes through; I'll still be keeping you posted.

**Comment by abo-abo** [comment]
I don't like this type of interface. So suppose the user decided that he needs `counsel-imenu`, key binding <kbd>C-c i</kbd>. But wait, he wants to jump immediately, so instead of using the associated key binding, he has to remember to:

1. Position the point on the item.
2. Press <kbd>C-u</kbd> <kbd>C-u</kbd> twice.
3. Press <kbd>C-c i</kbd>.

All this with no feedback or discovery.

Here's the type of interface I like: 

1. Press <kbd>C-c i</kbd>, the symbol-at-point is preselected (feedback and discovery).
2. Press <kbd>RET</kbd> if you made your decision.

Note that you still have an option to do something else after step 1. Not so with the first algorithm.  Even the key chord lengths don't add up: <kbd>C-u C-u C-c i</kbd> vs. <kbd>C-c i RET</kbd>.

**Comment by vermiculus** [comment]
Agree; closing.

**Pull request closed without merging**
