### PR TITLE
Add a command to switch to another git worktree.

### PR DESCRIPTION
**Pull request by mookid**

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. It looks like you don't have an Emacs Copyright Assignment yet. Since the package is on GNU ELPA, all contributions over 15 lines need a CA.

If you want to get the CA, see README for more info.

**Comment by mookid** [comment]
I actually started the procedure to get the paperwork done. I'll let you know when it is done.

**Comment by abo-abo** [comment]
Thanks.

**Comment by mookid** [comment]
@abo-abo : I received the assignment.

**Comment by abo-abo** [comment]
Thanks. Can you give me an example git tree workflow so I can test the code better. Right now I only have a single work tree in all my projects.

**Comment by mookid** [comment]
Sure. A sample example:

``` bash
cd /tmp
mkdir worktree_test
cd worktree_test
git init && echo test >> a.txt && git add a.txt && git commit -m test
git worktree add ../worktree1
git worktree add ../worktree2
```

**Comment by abo-abo** [comment]
Really cool, thanks.

**Pull request closed without merging**
