### PR TITLE
Work around current-kill pitfalls

### PR DESCRIPTION
**Pull request by basil-conto**
Re: #1523 
Cc: @DamienCassou 

I've tried to make the commit and source comments descriptive, but please let me know if you have any questions or issues.

### CODE REVIEW

**Comment by basil-conto** [comment]
@abo-abo I assume `counsel-yank-pop` is not the only Ivy-backed command whose actions (`counsel-yank-pop-action-remove`) can, when repeated via `ivy-dispatching-call`, result in an empty collection. Is this so? Either way, is this a problem?

**Comment by basil-conto** [comment]
Note that this PR does not address [bug#31097](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31097) and [bug#31209](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31209).

**Comment by abo-abo** [comment]
> I assume counsel-yank-pop is not the only Ivy-backed command whose actions (counsel-yank-pop-action-remove) can, when repeated via ivy-dispatching-call, result in an empty collection. Is this so?

Could be. You can also kill almost all your buffers with `ivy-switch-buffer`.

> Either way, is this a problem?

I don't think so.

**Comment by abo-abo** [comment]
Thanks.

**Comment by DamienCassou** [comment]
Thank you very much!

**Pull request merged**
