### PR TITLE
ivy.org manual edits

### PR DESCRIPTION
**Pull request by sjLambda**
Edits to documentation and manuals.

### CODE REVIEW

**Comment by sjLambda** [comment]
Uploaded after finishing CA paperwork with FSF.

**Comment by abo-abo** [comment]
Thanks a lot. I've added some minor fixes on top of your changes.

Hope to see more contributions from you in the future:)

**Comment by sjLambda** [comment]
Your welcome.

I could do more if not for the github overhead. For example, how do I merge
back your changes to ivy.org file back to my local repo on my laptop? I
hate to go through the github website UI. I'd rather type at the terminal.

--Lambda Coder.

**Comment by abo-abo** [comment]
The github overhead is just opening a web page and clicking "open pull request".

Everything else can be done from a terminal. Or with Magit, which I prefer.
For example, here's my `.git/config` for CIDER:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:abo-abo/cider.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	fetch = +refs/pull/*/head:refs/pull/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
	rebase = true
[remote "upstream"]
	url = https://github.com/clojure-emacs/cider
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "upstream"]
	remote = upstream
	merge = refs/heads/master
	rebase = true
```

My local repository has two remotes: `git@github.com:abo-abo/cider.git`, aka `master`, to which I have push access.  And `https://github.com/clojure-emacs/cider` aka `upstream`, to which I don't have push access.

To update my `master` to the changes in `upstream`, I do `git checkout upstream && git pull`, followed by `git checkout master && git rebase upstream`.

To open a PR, I commit stuff to my local `master`, making sure that it's rebased against the current `upstream`; `git push` to update `git@github.com:abo-abo/cider.git` to my local master; and click the "open PR" button.

**Comment by antonio** [comment]
> The github overhead is just opening a web page and clicking "open pull request".

And not even that:

**Comment by abo-abo** [comment]
@antonio Thanks for the suggestion, it's pretty cool.

**Comment by sjLambda** [comment]
Yes @antonio that's cool. I like that clever replace-regexp.

**Comment by abo-abo** [comment]
@sjLambda Hi. I've made significant edits to ivy.org. It now exports both to ivy.info and to http://oremacs.com/swiper/ as HTML.

Check it out if you have the time, perhaps you'll have some corrections.

**Comment by sjLambda** [comment]
Oleh, cool. I just sent you a pull request with my edits. Hope you can
incorporate them. --sjLambda

**Pull request closed without merging**
