### PR TITLE
Implements auto resize feature.

### PR DESCRIPTION
**Pull request by jcs090218**
I think this should work for #649. Can you check this patch? Thanks!

*P.S. Anyway, I don't know where I should place my code hence I created a new file for it.*

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks for the PR. But I prefer to avoid doing extra work in `post-command-hook`. Please review the referenced commit and see if it works for you.

**Comment by jcs090218** [comment]
Thanks to have this feature! It works except when the frame's size changed. I solved it by implemented the shrink to `window-size-change-functions`. Do you think you can implement this feature too? Thanks! :D

**Comment by jcs090218** [comment]
@abo-abo Just wonder if you have any thoughts about this? Thanks! :grin:

**Comment by abo-abo** [comment]
Sounds good to modify `window-size-change-functions` for the duration when ivy is active.

Could you please PR with a modification to `ivy--minibuffer-setup` and `ivy--cleanup`?

**Comment by jcs090218** [comment]
I made the PR, but I don't know if this is what you want? I think it is good to have you implemented yourself since I don't think I can code better `elisp` than you! Anyway, I tried! :grimacing:

**Comment by abo-abo** [comment]
Thanks for the implementation and the testing.

**Pull request closed without merging**
