### PR TITLE
Tweak counsel-find-file-delete

### PR DESCRIPTION
**Pull request by basil-conto**
Please review each commit in turn.

Re: #1774 
Cc: @ChoppinBlockParty

### CODE REVIEW

**Comment by basil-conto** [comment]
I ran into the following `dired-delete-file` quirk:

1. `make plain`
2. <kbd>C-x</kbd><kbd>d</kbd>`//tmp`<kbd>RET</kbd>
3. <kbd>+</kbd>`foo`<kbd>RET</kbd>
4. <kbd>C-x</kbd><kbd>C-f</kbd>`foo`<kbd>C-j</kbd>`bar`<kbd>RET</kbd>
5. <kbd>C-o</kbd><kbd>C-x</kbd><kbd>C-s</kbd>
6. <kbd>C-x</kbd><kbd>C-f</kbd><kbd>DEL</kbd>`foo`
7. <kbd>M-o</kbd><kbd>k</kbd>
   * Expected Dired prompt: "Recursively delete /tmp/foo/? (yes, no, all, quit, help)"
   * Actual Dired prompt: "Recursively delete ? (yes, no, all, quit, help)"

This is due to the implementation of `dired-make-relative`.

One option is to hot-swap it with `file-relative-name`:

```diff
diff --git a/counsel.el b/counsel.el
index bfa63ac..2fd7089 100644
--- a/counsel.el
+++ b/counsel.el
@@ -1742,7 +1742,8 @@ counsel-find-file-delete
             ;; `dired-delete-file', which see, already prompts for directories
             (eq t (car (file-attributes x)))
             (counsel--yes-or-no-p "Delete %s? " x))
-    (dired-delete-file x dired-recursive-deletes delete-by-moving-to-trash)
+    (cl-letf (((symbol-function 'dired-make-relative) #'file-relative-name))
+      (dired-delete-file x dired-recursive-deletes delete-by-moving-to-trash))
     (dired-clean-up-after-deletion x)
     (ivy--reset-state ivy-last)))
```

So long as you don't mind `/tmp/foo/` (the `default-directory`) being abbreviated as `./` and `/tmp/` (the parent directory) being abbreviated as `../`.

Another option is to pass the `directory-file-name` of the file/directory being deleted to `dired-delete-file`:

```diff
diff --git a/counsel.el b/counsel.el
index bfa63ac..9c55f8a 100644
--- a/counsel.el
+++ b/counsel.el
@@ -1742,7 +1742,9 @@ counsel-find-file-delete
             ;; `dired-delete-file', which see, already prompts for directories
             (eq t (car (file-attributes x)))
             (counsel--yes-or-no-p "Delete %s? " x))
-    (dired-delete-file x dired-recursive-deletes delete-by-moving-to-trash)
+    (dired-delete-file (directory-file-name x)
+                       dired-recursive-deletes
+                       delete-by-moving-to-trash)
     (dired-clean-up-after-deletion x)
     (ivy--reset-state ivy-last)))
```

So long as you don't mind the missing trailing slash of directory names.

Yet another option is to leave things as they are, and hope the empty file name will make the user think twice about deleting the directory containing the file being visited by the current buffer.

Thoughts, @abo-abo, @ChoppinBlockParty, @DamienCassou?

**Comment by ChoppinBlockParty** [comment]
Good catch. I am wondering will `(expand-file-name x)` change the prompt?

**Comment by basil-conto** [comment]
No, it's already an absolute file name.

**Comment by ChoppinBlockParty** [comment]
Sorry for a dumb question. Thant looks like weird behavior, may be dired functions do not fit for ivy? Because I do not think that I can reproduce this with dired. May be we should use default functions like `delete-file` `delete-directory` and if for some reason use does not like this he can write his own more elaborated delete action?

**Comment by basil-conto** [comment]
> Thant looks like weird behavior

Yes, but don't forget that it's an unlikely edge-case, not the usual behaviour, and that there are workarounds.

> may be dired functions do not fit for ivy?

@DamienCassou argued in #1671 that `dired-delete-file` saves us having to reimplement directory deletion, which is a fair point. The source comments before `dired-delete-file` further encourage use of `dired-delete-file` outside of Dired. Besides, The quirk I described earlier can always be reported and fixed upstream, so that Counsel does not have to care about it forever.

> May be we should use default functions like `delete-file` `delete-directory`

Feel free to implement this if you're interested. But I don't think it's possible to do so as flexibly as `dired-delete-file` without duplicating the whole thing, which I would not agree with.

> if for some reason use does not like this he can write his own more elaborated delete action?

Yes, this is universally true in Emacs.

**Comment by ChoppinBlockParty** [comment]
@basil-conto I do not to be disturbing, it was just an opinion, please, feel free to merge your work, I find it very helpful and looking forward to try it out.

**Comment by basil-conto** [comment]
@ChoppinBlockParty No, I think there's truth to what you're saying, I just haven't had the time to look at this issue again; sorry for the delay.

**Comment by abo-abo** [comment]
Thanks, all.

**Pull request closed without merging**
