### PR TITLE
counsel.el (counsel--root-directory): Add

### PR DESCRIPTION
**Pull request by justbur**
Add option (counsel-show-root-directory) to show root directory in
prompt of relevant commands, counsel-git, counsel-git-grep and
counsel-ag.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks, I solved the problem in a slightly different, more customizable way.

**Comment by justbur** [comment]
I like it. Thanks

**Comment by abo-abo** [comment]
By the way, `(split-string directory "/")` doesn't look very portable. Did you test this on Windows?

**Comment by justbur** [comment]
I'll try to rewrite it

**Pull request closed without merging**
