### PR TITLE
Add a git-checkout wrapper.

### PR DESCRIPTION
**Pull request by mookid**
Also, some cleanup/simplifications in the second commit.

### CODE REVIEW

**Comment by dieggsy** [comment]
Doesn't `magit-checkout` already do this if you use ivy?

**Comment by mookid** [comment]
I am not a magit user, so I don't know; it probably does...

**Comment by abo-abo** [comment]
@mookid Thanks. Please review my fixes https://github.com/abo-abo/swiper/commit/82852271aab295c90fe461ae20d1c4957957ed8e.

**Comment by mookid** [comment]
here it is.

thanks!

**Pull request closed without merging**
