### PR TITLE
A color-moccur like display of counsel-ag/rg results.

### LINKED ISSUE #1655: Does ivy has similar search result rendering function like color-moccur?
I am walking through a package called `color-moccur` has a fantastic result output format. 

It separates the file paths and their line, making the output much clear, especially when we split the window. It will also colorize the matching part of the current buffer and the result buffer showing below. I am wondering if there is a similar rendering function in ivy?

image

### PR DESCRIPTION
**Pull request by mookid**
Fix #1655.

I did not figure out how to avoid introducing a new global (ivy--occur-press-orig-buffer).

Also, maybe more faces are needed? 
CC @ztlevi

### CODE REVIEW

**Comment by ztlevi** [comment]
@mookid Thanks mookid. How to test this one? I changed the `ivy`, `counsel`, `swiper` 's load path and then `(ivy-set-occur 'swiper 'counsel-ag-occur-color-moccur)`. But I get the following result by searching `soft` in `swiper` and it doesn't look right...

image

**Comment by mookid** [comment]
It won't work for swiper; the parser expects some grep-like output. I tested it with rg; I think that grep, git-grep or ag will do too.

Further code is needed if you want it to work with occur.

**Comment by ztlevi** [comment]
Sorry, I still don't get how to enable this one? Do mean `(ivy-set-occur 'counsel-rg 'counsel-ag-occur-color-moccur)` and then `M-x counsel-rg` will show the results like `color-mocuur`? And `ivy-occur` doesn't?

**Comment by mookid** [comment]
Funny fact: as counsel-rg is (badly?) implemented as 

```
(let ((counsel-ag-base-command counsel-rg-base-command))
    (counsel-ag initial-input initial-directory extra-rg-args rg-prompt))
```

the correct setup code is actually...
(ivy-set-occur 'counsel-**a**g 'counsel-ag-occur-color-moccur)

**Comment by ztlevi** [comment]
Damn, that's so weird...

What's your setup for this PR? There are missing lines in the `ivy-occur` buffer.
image

My swiper revision is  `da75e8dd2a48a9314806f85dad742d16b08d678c`.
Emacs version: GNU Emacs 26.1 (build 1, x86_64-apple-darwin18.0.0, Carbon Version 158 AppKit 1670) of 2018-09-29
OS: MacOS

**Comment by mookid** [comment]
ok I think that for the vanilla configuration this should fix it:

``` diff
@@ -4134,7 +4134,7 @@ There is no limit on the number of *ivy-occur* buffers."
 (defun counsel-ag--split-match (candidate)
   (let ((split (split-string candidate ":")))
     (when split
-      (list (car split) (cadr split) (mapconcat 'identity (nthcdr 3 split) ":")))))
+      (list (car split) (cadr split) (mapconcat 'identity (nthcdr 2 split) ":")))))

 (defun counsel-ag--display-match (loc-info text)
   (let ((current-line-display))
```

**Comment by mookid** [comment]
@abo-abo I wonder if the definition of `counsel-ag-command` could be added as part of the macroexpansion of `def-counsel-ag-command`; it would make different ag commands more independent from each other (it's weird that these share global state) and hide more of these implementation details.

**Comment by ztlevi** [comment]
Does `ivy-occur-press-and-switch (RET)` in ivy-occur buffer work? I get the proper occur buffer now but navigation doesn't work.

**Comment by mookid** [comment]
> Does `ivy-occur-press-and-switch (RET)` in ivy-occur buffer work? I get the proper occur buffer now but navigation doesn't work.

Can you please test again? I met another issue with the regexp.

**Comment by abo-abo** [comment]
@mookid Thanks for the contribution. I'm currently in the process of reviewing/adapting it. Please don't add new commits for a while.

Some changes I already did:

- put all functions that start with `counsel-` into counsel.el
- remove the `boundp` check from the new macro, it fails during compilation for me

Something I don't like that needs to be fixed:

- `ivy--occur-press-orig-buffer` is being used by `counsel-git-grep-action`. The action function should be generic, if it's used from the minibuffer, it should not know about the occur buffer, which doesn't exist.
- if `counsel-ag-occur-color-moccur` is superior, it should be used as a default

Something I like:

- Fixing the fact that `counsel-ag`, `counsel-rg` etc used a single caller for customization

Something I don't like:

- Using `pcase` in Ivy. I used to not like pattern matching before. I like it now, but I still feel that it could be a barrier to entry for new contributors. So I prefer to avoid it. For Emacs compatibility reasons as well.

**Comment by mookid** [comment]
> @mookid Thanks for the contribution. I'm currently in the process of reviewing/adapting it. Please don't add new commits for a while.

hey @abo-abo, thanks for the interest. I guess we can share this branch and stop rebasing to make progress efficiently.

**Comment by abo-abo** [comment]
@mookid, I've had a test run of the new function. Some questions:

1. What do we do about `wgrep`? Will it still work? Because if not, it's a significant trade-off.
2. I imagined that the highlights would be added not only for file names, but also for the search text. We can add them later though, because we don't rely on `font-lock` any more.

I've saved my work to `counsel-moccur` branch. We can continue from there. I think if Q1 is answered, we can merge, but I would prefer Q2 to be there as well.

**Comment by mookid** [comment]
@abo-abo 
+ about 1.: my quick investigation shows that redefininig `wgrep-line-file-regexp` is the way to go, but it would lead to ugly hacks: 

```
(defvar wgrep-line-file-regexp wgrep-default-line-header-regexp
  "Regexp that match to line header of grep result.

That capture 1: filename 3: line-number
End of this match equals start of file contents.
")
```

with that patch included, the file name is no longer part of the capture.

+ One alternative would be to toggle the display to the current one when entering wgrep mode; on the plus side, it ensures that no functionality is lost in the process. 


I think that this can be split in two: finishing the part about counsel-ag-* commands first (which is not related to the original issue anyway) and then going on on the new results display.

**Pull request closed without merging**
