### PR TITLE
Improve Swiper minibuffer highlighting

### PR DESCRIPTION
**Pull request by basil-conto**
### Commentary

`ivy-highlight-functions-alist` does (and probably should) not include an entry for `swiper--re-builder`, so highlighting always falls back to `ivy--highlight-default`, even when `ivy--regex-function` is set to, say, `ivy--regex-ignore-order`.

Temporarily updating `ivy-highlight-functions-alist` to include an entry for `swiper--re-builder` is one **suboptimal** way to adapt highlighting accordingly. @abo-abo Can you think of a better way to achieve this, short of redesigning the whole regexp-builder/highlight-function system?

Re: #1550

### Example

1. `make plain`
2. ```el
   (setf (alist-get t ivy-re-builders-alist) #'ivy--regex-ignore-order)
   ```
3. <kbd>C-j</kbd>
4. <kbd>C-x</kbd><kbd>C-f</kbd>`swiper.el`<kbd>RET</kbd>
5. <kbd>C-s</kbd>`swiper isearch with an overview`

#### Before

![before](https://user-images.githubusercontent.com/9121222/39532690-380b8d04-4e25-11e8-9b45-e4a04cdee406.png)

#### After

![after](https://user-images.githubusercontent.com/9121222/39532702-3d9458fa-4e25-11e8-9e75-b52dd8ce4baf.png)

### CODE REVIEW

**Comment by muirmanders** [comment]
Coincidentally, I started trying to fix regex-ignore-order highlighting in swiper recently. I was looking at the buffer highlighting first instead of the minibuffer highlighting. For highlighting, swiper seems to only support regex builders that return a single regex. In particular `swiper--update-input-ivy` takes the `caar` of the regex parts, discarding all but the first regex part in the case of ignore-order. `swiper--add-overlays` similarly only works with a single regex. I was reworking these to operate on a list of regex parts.

Should I pause my effort and see what happens with this PR, or do you think they are unrelated?

**Comment by basil-conto** [comment]
@muirmanders

> Should I pause my effort and see what happens with this PR, or do you think they are unrelated?

I opened this PR because I thought I had stumbled across a quick fix to minibuffer highlighting at least, but I was wrong. I'm not actually familiar with how everything interoperates and I don't currently have much free time, so please don't pause your efforts because of me.

> I'd like to contribute to making regex-ignore-order a first class regex option.

As a fellow user, I look forward to seeing the fruit of your efforts. Thanks for working on this.

**Comment by abo-abo** [comment]
> Thanks for working on this.

Same from me. I would love to get this fixed, but I don't have much free time in the coming week or two.

**Comment by basil-conto** [comment]
Seeing as I won't be working on this again in the immediately foreseeable future, should I close this PR, or would you rather it be kept open as a reminder?

**Comment by muirmanders** [comment]
If you are done with it, please close it.

**Pull request closed without merging**
