### PR TITLE
Navigate flycheck errors using counsel

### PR DESCRIPTION
**Pull request by rgrinberg**
Would be great to have this work with ivy-occur as well.

### CODE REVIEW

**Comment by rgrinberg** [comment]
I've tried to implement occur but it's not working. Could you have a look perhaps?

**Comment by abo-abo** [comment]
Thanks. I've made a fix to make `ivy-occur` work. Please test.

**Comment by abo-abo** [comment]
Now the error message is shown in place of the source code. I think it's better, since it's very easy to access the related source code.

**Comment by rgrinberg** [comment]
One reason why I wanted occur mode for the errors is that I wanted to fix them right in the occur buffer. In any case, I’ll trust your judgement here :)

**Pull request closed without merging**
