### PR TITLE
Keep this-command around for `ivy-read` as new input is typed

### PR DESCRIPTION
**Pull request by narendraj9**

### CODE REVIEW

**Comment by basil-conto** [comment]
@narendraj9 Please check that #1621 also addresses your concern.

**Comment by abo-abo** [comment]
Just merged #1621. Please check if this PR is still needed.

**Comment by basil-conto** [comment]
> Please check if this PR is still needed.

I don't think so, as both PRs seem to have the same goal.

**Comment by abo-abo** [comment]
OK, closing. @narendraj9 Thanks anyway:)

**Pull request closed without merging**
