### PR TITLE
counsel.el: Add counsel versions of org-goto

### PR DESCRIPTION
**Pull request by fabacino**
* counsel-org-goto: Go to headline in current org file
* counsel-org-goto-all: Go to headline in any open org file

With default settings, the output of `counsel-org-goto` is the same as in vanilla `org-goto` (without steps). Note that for huge files `counsel-org-goto` is considerably faster than its built-in friend, so it might be useful even if you don't want to customize the output.

```emacs-lisp
;; Example configuration
(setq counsel-org-goto-display-style 'path)
(setq counsel-org-goto-separator " ➜ ")
(setq counsel-org-goto-face-style 'org)
(define-key org-mode-map (kbd "C-c C-j") 'counsel-org-goto)
(define-key org-mode-map (kbd "C-u C-c C-j") 'counsel-org-goto-all)
```

This might be a solution for issue #986

### CODE REVIEW

**Comment by abo-abo** [comment]
Well done, thanks a lot.

**Comment by therockmandolinist** [comment]
This is really nice! Would it be possible to abbreviate/fontify links in headlines like org does? Right now links are displayed in the raw org syntax.

**Comment by fabacino** [comment]
@therockmandolinist I will take a look at it, thanks for your feedback!

**Comment by amosbird** [comment]
@fabacino Hi, this feature is nice. How about adding preview ability? Or have <tab> to preview selected items.

**Comment by Dickby** [comment]
I think i miss the point here. Can somebody tell me what's the difference between `counsel-org-goto` and `counsel-imenu` inside an org file if `org-imenu-depth` is set to a higher value?

**Comment by fabacino** [comment]
@Dickby As a wrapper around `org-goto`, `counsel-org-goto` provides a few options to customize its output (e.g. including keywords and tags, different ways of displaying headlines), while `counsel-imenu` is a much more generic way to list places where you can jump to.

In the end it depends whether any of the options of `counsel-org-goto` can provide some value to you. If you are fine with the output of `counsel-imenu` within org-mode, you probably won't need `counsel-org-goto`. Personally, I only use the latter, since I search for keywords quite often.

**Comment by amosbird** [comment]
Um, after doing an `ivy-call` and abort ivy, the point isn't restored to the original place.

**Comment by fabacino** [comment]
@amosbird I am not really sure what you mean by preview ability. Expanding the subtree of the selected headline? Please elaborate. I also suggest to open a new issue for that.

**Comment by amosbird** [comment]
@fabacino oh, I mean `ivy-call`.

**Comment by the42** [comment]
`org-refile` would also profit of this solution. Any chances to als provide a `counsel-org-goto` powered `counsel-org-refile` ?

**Pull request merged**
