### PR TITLE
Counsel compile further fixes

### PR DESCRIPTION
**Pull request by stsquad**
A small number of tweaks and fixes for better handling builds in subdirectories and recent history.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks.

**Comment by basil-conto** [comment]
@stsquad Can you please check the simplification I pushed in bc2dcbeae439a20ebaf6b270327999d258e16208?

How important is it to stat each file only once? If the answer is "not very", I think we can further simplify as follows:

```diff
diff --git a/counsel.el b/counsel.el
index 86e5264..339eb51 100644
--- a/counsel.el
+++ b/counsel.el
@@ -5425,15 +5425,14 @@ counsel--get-build-subdirs
   "Return all subdirs under BLDDIR sorted by modification time.
 If there are non-directory files in BLDDIR, include BLDDIR in the
 list as it may also be a build directory."
-  (let* ((files (directory-files-and-attributes
+  (let* ((files (directory-files
                  blddir t directory-files-no-dot-files-regexp t))
-         (dirs (cl-remove-if-not #'cl-second files)))
+         (dirs (cl-remove-if-not #'file-directory-p files)))
     ;; Any non-dir files?
     (when (< (length dirs)
              (length files))
-      (push (cons blddir (file-attributes blddir)) dirs))
-    (mapcar #'car (sort dirs (lambda (x y)
-                               (time-less-p (nth 6 y) (nth 6 x)))))))
+      (push blddir dirs))
+    (sort dirs #'file-newer-than-file-p)))
 
 (defun counsel-compile-get-build-directories (&optional dir)
   "Return a list of potential build directories."
```

**Comment by stsquad** [comment]
@basil-conto I'm probably not the best person to ask. stat on Linux is super cheap (and cached) but it might matter more for Windows users. Anyway we'll see if anyone complains about performance. Thanks for the clean-up.

**Comment by basil-conto** [comment]
@stsquad I was more worried about, say, remote filesystems, but either way it's probably best to keep the current implementation (the minor cleanup I pushed yesterday shouldn't affect performance). Thanks.

**Pull request closed without merging**
