### PR TITLE
swiper.el: modify isearch-string only when evil-search-module is isearch

### PR DESCRIPTION
**Pull request by edkolev**
Refs #1406

### CODE REVIEW

**Comment by edkolev** [comment]
Please let me know if I can improve the PR. I was considering using an `if` instead of 2 `whens`, but I settled on the 2 `when`s. Let me know if I should change that.

A bit more details about this change - https://github.com/abo-abo/swiper/pull/1406#issuecomment-364869959

**Comment by dieggsy** [comment]
@edkolev a lot of isearch internally uses isearch-string. Should we consider adding this regardless of evil, or is it intentionally left out otherwise?

**Comment by edkolev** [comment]
The way I see it, this PR (and the one ref-ed above) try to improve swiper integration with evil. I'd consider swiper integration with isearch in general out of the scope of this PR.

Also, isn't swiper an alternative to isearch, maybe it doesn't make a lot of sense to integrate them?

**Comment by abo-abo** [comment]
Thanks.

**Pull request closed without merging**
