### PR TITLE
Add counsel commands for jumping to files

### PR DESCRIPTION
**Pull request by justbur**
* counsel.el (counsel-file-jump): New command to jump to file in
  any sub directory
* counsel.el (counsel-dired-jump): New command to jump to any sub
  directory

### CODE REVIEW

**Comment by justbur** [comment]
These are pretty basic right now, but they work well for me

**Comment by abo-abo** [comment]
Thanks. It's quite similar to `find-file-in-project` though, which I prefer to use.

**Comment by abo-abo** [comment]
Also, have a look at my 2 subsequent commits, I've updated your functions a bit.

**Comment by justbur** [comment]
I wanted something that doesn't depend on being in a project, and for how simple this is it's surprisingly quick for me still.

**Pull request merged**
