### PR TITLE
fix counsel-evil-registers and implement counsel-evil-marks

### PR DESCRIPTION
**Pull request by mohkale**
this pull request addresses issues [2246](https://github.com/abo-abo/swiper/issues/2246) & [2221](https://github.com/abo-abo/swiper/issues/2221). 

I've abstracted out a lot of the code in `counsel-mark-ring` to minimise the amount of code duplication in `counsel-evil-marks`.

~~Full disclosure, I can't seem to pass all the tests cases. Test 45 keeps failing for me with the error trace:~~

```
Test ivy-swiper-wgrep backtrace:
  signal(error ("Package wgrep isn’t installed"))
  apply(signal (error ("Package wgrep isn’t installed")))
  (setq value-1152 (apply fn-1150 args-1151))
  (unwind-protect (setq value-1152 (apply fn-1150 args-1151)) (setq fo
  (if (unwind-protect (setq value-1152 (apply fn-1150 args-1151)) (set
  (let (form-description-1154) (if (unwind-protect (setq value-1152 (a
  (let ((value-1152 (quote ert-form-evaluation-aborted-1153))) (let (f
  (let* ((fn-1150 (function string=)) (args-1151 (condition-case err (
  (let ((search-cmd (car --dolist-tail--))) (let* ((fn-1150 (function
  (while --dolist-tail-- (let ((search-cmd (car --dolist-tail--))) (le
  (let ((--dolist-tail-- (quote (swiper swiper-isearch)))) (while --do
  (closure (t) nil (let ((--dolist-tail-- (quote (swiper swiper-isearc
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name ivy-swiper-wgrep :documentation nil :
  ert-run-or-rerun-test(#s(ert--stats :selector (not ivy--lazy-load-ff
  ert-run-tests((not ivy--lazy-load-ffap--ffap-url-p) #f(compiled-func
  ert-run-tests-batch((not ivy--lazy-load-ffap--ffap-url-p))
  (ert-stats-completed-unexpected (ert-run-tests-batch test-set))
  (+ unexpected (ert-stats-completed-unexpected (ert-run-tests-batch t
  (setq unexpected (+ unexpected (ert-stats-completed-unexpected (ert-
  (let ((test-set (car --dolist-tail--))) (setq unexpected (+ unexpect
  (while --dolist-tail-- (let ((test-set (car --dolist-tail--))) (setq
  (let ((--dolist-tail-- test-sets)) (while --dolist-tail-- (let ((tes
  (let ((test-sets (quote (ivy--lazy-load-ffap--ffap-url-p (not ivy--l
  ivy-test-run-tests()
  command-line-1(("-l" "elpa.el" "-l" "colir.el" "-l" "ivy-overlay.el"
  command-line()
  normal-top-level()
Test ivy-swiper-wgrep condition:
    (error "Package wgrep isn’t installed")
   FAILED  45/54  ivy-swiper-wgrep
```

~~this is the only test that's failing and I have installed `wgrep` which I've verified by opening emacs and running `M-: (require 'wgrep)` without any errors, so I'm not sure why this is happening. I'd like to ask you run the tests yourself before accepting this request. There aren't any compilation warnings.~~

~~Update: yeah, I tried cloning you're repository ([abo-abo/swiper](https://github.com/abo-abo/swiper)) & running the tests again and test 45 is still failing for me, so I can only surmise my code has nothing to do with it 😌.~~

### CODE REVIEW

**Comment by MoHKale** [comment]
Okay... Didn't notice this repo had continuous integration. Disregard my point about test 45. All tests seem to be passing on here & I guess that means their fine 😄😄😄.

**Comment by abo-abo** [comment]
Thanks. Do you have an Emacs CA? See README for details.

**Comment by MoHKale** [comment]
oh, I never read up on what legally significant meant... my bad. I'll apply for the paperwork now & done. now I just have to wait for them to mail me the paperwork (I think) 😢. I'll update this when it's done.

**Comment by abo-abo** [comment]
Thanks.

**Comment by MoHKale** [comment]
finally got CA, will resolve conflicts and push tommorow.

**Comment by MoHKale** [comment]
Okay, I'm ready to merge.

NOTE: I've also introduced a new face for evil-registers called `counsel--evil-register-face` because as it stood evil registers looked to plain to properly stand out. For now I've just had it inherit the heading 1 face, because that looks good with my theme... but you'll probably want to change it to something more consistent.

I wasn't sure how to present my CA so I've just emailed it to you. let me know if there are any issues.

**Comment by abo-abo** [comment]
Thanks, sorry for the late review. Please test again.

I've made several code quality improvements. Please review.

In the future, I suggest to split the changes into smaller atomic commits.
One nice rule that I try to follow is to split away the "refactor" commits that have to influence at all on the functionality. Example: "counsel.el (counsel-mark--get-candidates): Extract".
This way, it's much easier to review the "actual" commits that change or add functionality.

**Comment by mohkale** [comment]
Understood. Sorry for the bunched commits. The refactoring was done entirely to ease support for the evil registers functionality and I thought it wouldn't make much sense unless I did them both together. In future I'll make sure to seperate refactoring from feature additions. 😃.

Everything seems to be working so far. Thnx for all the great work. `ivy`s the best 👍.

**Pull request closed without merging**
