### PR TITLE
Add support for browsing compilation errors

### PR DESCRIPTION
**Pull request by rgrinberg**
`counsel-compilation-errors` allows to navigate through the errors of
`M-x compile`.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. I suggest using `(counsel--compilation-errors-buffer (current-buffer))` in place of looking through all buffers.

Do you have an Emacs CA? See the README for more info.

**Comment by rgrinberg** [comment]
Thanks for the quick response.

> Thanks. I suggest using (counsel--compilation-errors-buffer (current-buffer)) in place of looking through all buffers.
We can have a version that does this as well, but it’s actually a lot less useful to me. It’s usually the case that I’m navigating source code and would prefer not to find the compilation buffer before jumping to the error. However, there’s no reason why we can’t have both versions.

By the way, another improvement that I would love to make is to actually include the error rather than just its location. Unfortunately, compilation-mode is not letting me extract information easily.
> Do you have an Emacs CA? See the README for more info.

No, I don’t. Thanks I will try to get on that ASAP.

**Comment by abo-abo** [comment]
> No, I don’t. Thanks I will try to get on that ASAP.

Thanks in advance.

**Comment by rgrinberg** [comment]
I completed the reassignment process :)

**Comment by abo-abo** [comment]
Thanks. Please review my refactor of your change. And the follow up commit, which adds more info to the completion candidates. I was testing with pylint, and I was able to filter out errors by type.

**Comment by rgrinberg** [comment]
Your commit looks good. Thanks!

**Pull request closed without merging**
