### PR TITLE
Preselect current theme

### PR DESCRIPTION
**Pull request by bcmertz**
Small change to preselect the current theme in `counsel-load-theme`

### CODE REVIEW

**Comment by basil-conto** [comment]
Thanks, but wouldn't the current theme be the last one the user would want to load? :)

**Comment by bcmertz** [comment]
Hmm good point, my thinking was that there should be some indicator of what the current theme is, perhaps instead of preselecting the current theme it could be listed in the prompt? Either way is fine by me, I'll just use the custom theme picker you helped me write :)

**Comment by basil-conto** [comment]
> there should be some indicator of what the current theme is, perhaps instead of preselecting the current theme it could be listed in the prompt

Keep in mind that there could be more than one enabled theme - in which case they should all be listed.

There's some precedent for listing options like this in the prompt in e.g. `swiper-multi`, `counsel-org-tag`, etc. if you'd like to try that out.

**Comment by bcmertz** [comment]
Good point! Thanks for the feedback!

**Pull request closed without merging**
