### PR TITLE
counsel.el: Add a generic minibuffer history browser.

### PR DESCRIPTION
**Pull request by jeberger**
This supersedes counsel-shell-command-history and counsel-expression-history with a generic counsel-minibuffer-history function that works for all minibuffer situations.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. The changes look good, but it seems you're not on `copyright.list`. Are you willing to get an Emacs Copyright Assignment?

**Comment by jeberger** [comment]
Sure, how do I go about it?

**Comment by abo-abo** [comment]
You fill in a form and send it by email. Instructions here: https://github.com/abo-abo/swiper#copyright-assignment.

**Comment by jeberger** [comment]
I just got the confirmation email from the FSF, so I should be on `copyright.list` shortly if I'm not already.

**Comment by abo-abo** [comment]
> I just got the confirmation email from the FSF, so I should be on copyright.list shortly if I'm not already.

Thanks for the update and the effort. You're not there yet, I just checked.

**Comment by manuel-uberti** [comment]
Any update on this one? Just curious. :)

**Comment by abo-abo** [comment]
@jeberger I keep checking `copyright.list` but you're still not there.
Please ask `assign@gnu.org` to make sure your email used for this commit is on the list (jeberger at free dot fr).

**Comment by jeberger** [comment]
That is the address I used when communicating with the FSF. I've just written to `assign@gnu.org` to ask them to check.

**Comment by jeberger** [comment]
Just got an email from `assign@gnu.org` saying that I am now on `copyright.list`

**Comment by abo-abo** [comment]
The assignment is finally updated, you're the last one on the list currently:) Thanks for the contribution!

> ivy-dynamic-exhibit-delay-ms

I've reset it to 0 by default: I could really feel the difference in `counsel-grep` when it was 500ms.

**Pull request closed without merging**
