### PR TITLE
counsel.el: Support amx in addition to smex

### LINKED ISSUE #1557: Amx support for counsel
I am wondering that smex is not actively maintained anymore and the new fork/substitution project is supposed to be amx that is very active right now.
Is it there any plan to support amx in a near/medium future? The interface is pretty much the same as I could see, so the implementation should be relatively simple.
Very thanks

### PR DESCRIPTION
**Pull request by basil-conto**
(`counsel--M-x-externs`): New function.
(`counsel-M-x`): Use it.  Conditionally call `amx-rank` or `smex-rank`, when available, from the action function.

Borrowing heavily from and building on the work and suggestions of @Ergus in #1580.

Fixes #1557.

### CODE REVIEW

**Comment by manuel-uberti** [comment]
Anything? :)

**Comment by basil-conto** [comment]
> Anything? :)

I think @abo-abo has been busy/AFK these days; let's be patient. :)

**Comment by abo-abo** [comment]
> I think @abo-abo has been busy/AFK these days; let's be patient. :)

I've been on vacation for 2 weeks. Got 62 unread issues/pull requests greeting me when I came back. Down to 30 unread ones by now:)

**Comment by abo-abo** [comment]
Thanks all.

**Comment by basil-conto** [comment]
> I've been on vacation for 2 weeks. Got 62 unread issues/pull requests greeting me when I came back. Down to 30 unread ones by now:)

Power to you. :)

**Comment by manuel-uberti** [comment]
Fantastic, thanks guys. 

Also, hope you enjoyed your holiday ☺️

**Pull request closed without merging**
