### PR TITLE
counsel.el (counsel-find-file): Add new action counsel-find-file-as-root

### PR DESCRIPTION
**Pull request by fabacino**
Adds a new action to `counsel-find-file` to open a file with root privileges.

### CODE REVIEW

**Comment by therockmandolinist** [comment]
It would be nice if files that required root access prompted for it automatically... is this possible?

**Comment by abo-abo** [comment]
Thanks. I wonder if `counsel-root-command` is really necessary. Do other systems have an alternative to `sudo`?

**Comment by fabacino** [comment]
@therockmandolinist I would suggest using a wrapper around `counsel-find-file-as-root` and calling that function explicitly when you need root privileges, maybe something like this:

``` elisp
(defun my/open-as-root ()
  (interactive)
  (when (and buffer-read-only
             buffer-file-name)
    (counsel-find-file-as-root buffer-file-name)))
(global-set-key (kbd "<f12>") 'my/open-as-root)
```

I would advise against automatically enabling root access to every file you open, but if you really want to do this, you could use pretty much the same function as an `:after` advice for `find-file`.

**Comment by fabacino** [comment]
@abo-abo I though some users might prefer `su` over `sudo`, that's why I didn't hard code it.

**Comment by abo-abo** [comment]
But does `su` work the same way? I thought `su` was only usable without an argument.

**Comment by fabacino** [comment]
`su` works as well, `/su::/path/to/file` expands to `/su:root@localhost:/path/to/file`.

**Comment by abo-abo** [comment]
I see, so it's Emacs magic. Thanks.

**Pull request closed without merging**
