### PR TITLE
Add command `counsel-mark-ring'

### PR DESCRIPTION
**Pull request by akermu**

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. Can you get the Emacs Copyright Assignment? See the README for more info.

Also, `(delete-dups mark-ring)` improves the command.

**Comment by joedicastro** [comment]
Well, congratulations, this one command was in my TODO list, you got there first! Well done!

**Comment by akermu** [comment]
I updated the PR with the suggestion of abo-abo and requested the CA from the FSF.

**Comment by abo-abo** [comment]
@akermu Thanks.

**Comment by akermu** [comment]
I got the CA from the FSF, do I have to post it here, @abo-abo?

**Comment by abo-abo** [comment]
@akermu Thanks, I see the CA. The commit is merged. One suggestion for improvement: sort the marks by their location, so that going up/down in candidate list also goes up/down in the buffer.

**Pull request closed without merging**
