### PR TITLE
support imenu

### PR DESCRIPTION
**Pull request by redguardtoo**

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. Do you have an Emacs CA? It's needed for changes >15 lines, since the package goes into GNU ELPA.

**Comment by redguardtoo** [comment]
Yes, I did this when I contributing js2-mode.

**Comment by redguardtoo** [comment]
I can forward you my signed document scanned copy if needed.

**Comment by abo-abo** [comment]
Thanks!

**Comment by dgutov** [comment]
:sparkles:

**Pull request merged**
