### PR TITLE
Added three new counsel commands.

### PR DESCRIPTION
**Pull request by joedicastro**
Added  these three new counsel commands `counsel-colors-web`, `counsel-colors-emacs` and `counsel-faces`.

### counsel-colors-emacs

counsel-colors-emacs

Show a list of all supported colors for a particular frame. This is very useful when developing a new theme, package or dealing with your configuration. This replaces the `helm-colors`, `anything-colors` and the default Emacs `list-color-display`. The colors available are different when you are on a terminal session or in a GUI one, this can be very helpful when developing a theme/package to test the compatibility.
 
### counsel- colors-web

counsel-colors-web

Show a list of all W3C web colors for use in CSS. This is very useful for web developers.
These are the colors defined by the W3C consortium to use in CSS sheets. All of these colors are compatible with any common browser.  The colors gray, green, maroon and purple have alternative values as defined by the X11 standard, here they follow the W3C one.

### counsel-faces

counsel-faces

Show a list of all defined faces. Also very useful when developing a theme/package. This replaces the commands `helm-colors`, `anything-colors` and the Emacs default `list-faces-display`. 

All of the command have several actions suited to the given context.

P.S. I already send by email the signed PDF for the FSF Copyright Assignment. They offer you this option now by default. I'm waiting an answer.

### CODE REVIEW

**Comment by abo-abo** [comment]
Looks very impressive. Thanks a lot.

**Comment by joedicastro** [comment]
You're welcome, I hope that this would the first from a lot more. I'll tell you when I hear something from FSF.

**Comment by joedicastro** [comment]
I received right now the FSF notification that the assignment process is complete. Seems that now the process is really fast, if we not count the weekend in the middle, there were only three days.

**Comment by abo-abo** [comment]
Merged, thanks again.

I rewrote `counsel-faces` slightly, please check.

**Comment by joedicastro** [comment]
Oh, thanks to you, now is way better!

I didn't know how to do that, I still have to learn a lot about how Emacs works and Emacs Lisp. 👍

**Comment by glucas** [comment]
These are cool commands, thanks for adding.

**Comment by joedicastro** [comment]
@glucas You're welcome! :smile:

**Pull request closed without merging**
