### PR TITLE
familiar isearch key bindings while helm is active

### PR DESCRIPTION
**Pull request by killdash9**

### CODE REVIEW

**Comment by killdash9** [comment]
I just noticed a problem with this patch.  Working on a fix.

**Comment by abo-abo** [comment]
Thanks, I've gone though with it and added this to my config:

```cl
(global-set-key "\C-s" 'swiper)
```

Before it was just <kbd>C-r</kbd>.

**Comment by killdash9** [comment]
That's not what this patch does.  This patch adds those bindings to the keymap used by helm while helm is active.  It reimplements the isearch behavior where you can press C-s repeatedly to advance to the next match in the file.

**Comment by abo-abo** [comment]
I get what it does:). There's just little point in binding `swiper` to <kbd>C-s</kbd> if the second
<kbd>C-s</kbd> won't work.

**Comment by killdash9** [comment]
The second C-s *does* work.  That's what this patch enables.

**Comment by abo-abo** [comment]
Yea, I got that. That's why i merged it (with a tiny change).

**Comment by killdash9** [comment]
Got it.  Sorry, didn't notice you had merged it.  Thanks for the great tool!

**Pull request closed without merging**
