### PR TITLE
counsel.el (counsel-cd-to-current-buffer, counsel-ag-map) (counsel-git-grep-map): Allow grep-like command to switch to the directory of the currently visited buffer.

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by abo-abo** [comment]
What's the use case for this?

**Comment by xuhdev** [comment]
Quickly switch to current directory for search. If the directory in a git repo is deep, it might take a while to use `counsel-cd` to switch to somewhere close to the directory of the current buffer. Life might be simply easier when there is a way to quickly jump to the directory of the current buffer.

**Comment by xuhdev** [comment]
Alternatively we can have this feature in `counsel-cd` (quickly replace the content of the minibuffer with the current directory)

**Comment by abo-abo** [comment]
> Alternatively we can have this feature in `counsel-cd` (quickly replace the content of the minibuffer with the current directory)

Nice idea. I've implemented it. Thanks, and please test.

**Pull request closed without merging**
