### PR TITLE
Use Ivy to browse eshell and shell history entries

### PR DESCRIPTION
**Pull request by manuel-uberti**
I am still waiting for the CA, but in the meantime I'm opening this PR as a reminder.

If you need me to fix anything in this commit, feel free to ask.

### CODE REVIEW

**Comment by manuel-uberti** [comment]
Paper signed and sent, waiting for a reply.

**Comment by abo-abo** [comment]
OK, thanks. It might take a while, make sure to email them if you get nothing for a month.

**Comment by manuel-uberti** [comment]
Just got the email with the confirmation. Don't know how you can check whether I'm telling the truth or not, though. :)

**Comment by abo-abo** [comment]
I can check:). Is `manuel@boccaperta.com` the email that you used? I don't see it yet. It might take a day or two to propagate to `gnuorg/copyright.list`, ping the FSF guy otherwise.

**Comment by manuel-uberti** [comment]
Yes, that's the email.

**Comment by abo-abo** [comment]
Better ping the guy, just to make things faster. If I remember correctly, it took a week for @justbur email to appear on the list. But it took less in other cases.

**Comment by manuel-uberti** [comment]
Well, he just wrote me with all the papers, I'll give it a day or two. Don't want to sound too impatient, he really was quick with my emails. :)

**Comment by abo-abo** [comment]
OK, it's good to see they're much faster now than a few years ago when I got my CA.

**Comment by manuel-uberti** [comment]
I pinged the guy. No answer. Don't know if my name is there on the list yet.

**Comment by abo-abo** [comment]
Not yet. The file shows up as updated today, but your email isn't there yet.

**Comment by manuel-uberti** [comment]
Any news here? I still have no answer from the guy.

**Comment by abo-abo** [comment]
Nope, still no change in the list.

**Comment by manuel-uberti** [comment]
Yay! What a coincidence, I just got my answer: my name has been added to the list. :)

**Comment by abo-abo** [comment]
Ah, I finally see it. Welcome to the club!

**Comment by abo-abo** [comment]
Please look at the clean-up commit. The main thing is to do `make compile` to check that your change does not introduce warnings.

**Comment by manuel-uberti** [comment]
Thank you. 
I didn't know about `make compile`, could have save you some work there. Sorry.

**Comment by abo-abo** [comment]
No problem, thanks for the contribution. Also, there's `make test`. Travis CI checks it for you, but it doesn't hurt to run it on your own machine.

**Pull request closed without merging**
