### PR TITLE
counsel.el (counsel-locate-cmd-es): Match path

### PR DESCRIPTION
**Pull request by et2010**

### CODE REVIEW

**Comment by basil-conto** [comment]
Just out of curiosity, because I'm not a Windows user: is the ".exe" suffix required to locate/execute executables?

**Comment by et2010** [comment]
It seems you can execute without the suffix. I didn't notice any differences.

**Comment by abo-abo** [comment]
Could you please explain what "match path" means? More precisely, what is the change in behavior when adding the `-p` flag?

**Comment by et2010** [comment]
Sorry for the confusing description. With this flag, the parent folders containing the searched string will also be matched

image

For comparison, here's when this flag was removed:

image

**Comment by abo-abo** [comment]
Thanks, I assume here that all users will want `-p` flag. If there's an objection later on, we can extract the command into a customizable variable.

**Pull request closed without merging**
