### PR TITLE
add highlighter function configuration to ivy

### LINKED ISSUE #654: Font lock problem of `ivy--regex-ignore-order`
Hi,

It seem that the font lock works unexpectedly when using `ivy--regex-ignore-order`.

screen shot 2016-09-07 at 08 10 44

I guess `file` and `expand` should be highlighted ?

Minimum config for reproducing can be

```
(require 'package)

(setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                         ("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")))

(package-initialize)

(unless (and (file-exists-p (expand-file-name "elpa/archives/marmalade" user-emacs-directory))
             (file-exists-p (expand-file-name "elpa/archives/gnu" user-emacs-directory))
             (file-exists-p (expand-file-name "elpa/archives/melpa" user-emacs-directory))
             (file-exists-p (expand-file-name "elpa/archives/org" user-emacs-directory)))
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(setq use-package-verbose t
      use-package-enable-imenu-support t)
(require 'use-package)

(use-package swiper
  :ensure t
  :bind (("C-s" . swiper))
  :init (setq ivy-height 15
              ivy-count-format "(%d/%d) "
              ivy-use-virtual-buffers t
              ivy-initial-inputs-alist nil
              ivy-re-builders-alist '((t . ivy--regex-ignore-order))
              swiper-include-line-number-in-search t))
```

Thanks !

### PR DESCRIPTION
**Pull request by jyp**
This fixes #654 

It also somewhat simplifies the logic assigning highlighter for swiper.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks, but some tests are failing. You can `make test` to check your work.

Additionally, you'll need an Emacs Copyright Assignment for changes >15 lines, see the README for more info.

**Comment by jyp** [comment]
I could fix the tests for emacs 25 and 24.5, but older versions somehow do not work. What do you recommend to debug code for old emacs versions?

Besides, I have requested a copyright assignment form.

**Comment by abo-abo** [comment]
> I could fix the tests for emacs 25 and 24.5, but older versions somehow do not work. 

This might be good enough. As long as 25 and 24.5 pass, I can understand what needs to be done.

> What do you recommend to debug code for old emacs versions?

I recommend having a reproducible config that you're comfortable with, and having 2-3 versions of this config with ELPA packages and all.  Since byte-compiled Emacs code is not compatible between Emacs versions.

Other than that, just start the appropriate Emacs version and eval the failing test, try to step in etc.

> Besides, I have requested a copyright assignment form.

Thanks, let me know when it's done.

**Comment by jyp** [comment]
I have received confirmation from FSF that they have processed my copyright assignment, so this PR is legally mergeable.

**Comment by abo-abo** [comment]
Thanks. Can you please ask them to update the `copyright.list` file on fencepost? I don't see your name there yet.

**Comment by jyp** [comment]
The copyright clerk assures that I am now on the list

**Comment by abo-abo** [comment]
Thanks, I see it now as well.

Unfortunately, the patch doesn't rebase cleanly anymore. Could you please do a manual rebase of your changes on top of the current master and update the PR?

**Comment by jyp** [comment]
I have done the rebase.

**Comment by abo-abo** [comment]
Thanks. I think we can maybe avoid adding `highlighter` to `ivy-state` and to the arglist of `ivy-read`.
Since it's easily calculated from `ivy--regex-function`, we can do it like that.

The reasons are:

1. Adding an extra arg to `ivy-read` that won't be used often distracts from the other args.
2. Adding a new member to `ivy-state` can require a byte recompilation of all packages that use ivy. I did so a month ago and I still keep getting bug reports for that.

**Comment by jyp** [comment]
Well, the problem that this PR attacks is the following:

- users of ivy can override the re-builder (regex function)
- there is code in ivy which computes the highlighter from the re-builder
- but: the re-builder can be any function, and therefore it is impossible
for ivy to correctly take into account all cases
- my analysis is that the interface needs either to:
 - restrict re-builder to a fixed set or
 - allow customization of the highlighter

See also my comment in: https://github.com/abo-abo/swiper/issues/654

I did not see how to restrict the interface, thus this PR is precisely
about making it more flexible. Perhaps you have an idea on how to get rid
of swiper--re-builder?

**Comment by jyp** [comment]
I tested the PR on darwin, and it works great with python 3.5 👍
 However I got the following strange error with 2.7:
```
    import tensorflow as tf
  File "/nix/store/qprvcgvh7l0rw99ywnzcr5f9fkqrwsm9-python-2.7.12-env/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/nix/store/qprvcgvh7l0rw99ywnzcr5f9fkqrwsm9-python-2.7.12-env/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/nix/store/qprvcgvh7l0rw99ywnzcr5f9fkqrwsm9-python-2.7.12-env/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/nix/store/qprvcgvh7l0rw99ywnzcr5f9fkqrwsm9-python-2.7.12-env/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/nix/store/qprvcgvh7l0rw99ywnzcr5f9fkqrwsm9-python-2.7.12-env/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/nix/store/qprvcgvh7l0rw99ywnzcr5f9fkqrwsm9-python-2.7.12-env/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): no suitable image found.  Did find:
	/nix/store/qprvcgvh7l0rw99ywnzcr5f9fkqrwsm9-python-2.7.12-env/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: file too short
```

**Comment by jyp** [comment]
Pressing a little bit to avoid getting this PR lost in the abyss of time... :)
Do you think that my analysis makes sense?

**Comment by abo-abo** [comment]
It won't get lost, don't worry.

I'm happy with the interface the re-builder is selected with:

1. The package writer should almost never use the `:re-builder` arg to
   `ivy-read`, so that the user can always have his chosen re-builder
   with all commands. However, if there's a very specific reason the
   custom re-builders can't work, the author can make the restriction.

2. The user can customize re-builder per-command, and easily select it for all commands.

I want the same for the highlighters: have an alist variable with keys
being the re-builder functions, and values being the highlighter
functions. This way:

1. The user can still fine-tune the highlighter. But everything will
   work without any need for customization.

2. The author doesn't have to be bothered examining the extra args to
   `ivy-read`, since the highlighter is specified only via the alist,
   not via the args.

I could even think of removing the `:re-builder` out of `ivy-read`
arglist if not for compatibility issues.

If you have the time, please update the PR to have all customization go through e.g. `ivy-highlight-functions-alist`.

**Comment by jyp** [comment]
I think this makes sense. I'll try to give it a go!

**Comment by jyp** [comment]
Ok, I've updated the code as you asked (ifaiu). Let me know what you think.

**Comment by abo-abo** [comment]
Thanks. Please check my changes on top of your commit.

**Comment by jyp** [comment]
Your commit has reintroduced the bug. There are two problems with your changes:

1. When swiper is active (or indeed when the re-builder is customized), ivy--old-re is not correctly set. To fix the issue you can change the condition back to what it was at line 2458:

```
        (setq ivy--old-re
              (if (eq ivy--highlight-function 'ivy--highlight-ignore-order)
                  re
                (if ivy--old-cands
                    re-str
                  "")))
```

2. Setting the ivy--highlight-function when swiper is active does not work when ignoring the order. To fix the problem you can put code akin to the following around line 1548:

```
(if (and (eq ivy--regex-function 'swiper--re-builder)
                   (eq (cdr (assoc t ivy-re-builders-alist))
                       'ivy--regex-ignore-order))
              #'ivy--highlight-ignore-order
```

**Comment by abo-abo** [comment]
Thanks, could you open a new PR with these changes?

**Pull request closed without merging**
